# Generated by Django 5.1.5 on 2025-01-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Color', 'Color'), ('Size', 'Size')], max_length=100),
        ),
    ]
