# Generated by Django 5.1.5 on 2025-01-19 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 19, 15, 58, 31, 147758)),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 19, 15, 58, 31, 147805)),
        ),
        migrations.AlterField(
            model_name='variation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 19, 15, 58, 31, 148501)),
        ),
    ]
