# Generated by Django 5.1.5 on 2025-01-26 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 11, 0, 50, 355950)),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 11, 0, 50, 355988)),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 11, 0, 50, 357245)),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 11, 0, 50, 357263)),
        ),
        migrations.AlterField(
            model_name='variation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 11, 0, 50, 356674)),
        ),
    ]
