# Generated by Django 5.1.5 on 2025-01-24 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0020_cartitem_user_alter_cart_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 2, 54, 1, 817745)),
        ),
    ]
